### ISSUE TITLE
Version solving failed with flutter_test

### ISSUE THREAD

**Issue by badrobot15** [BendixMa/ink_page_indicator#2]
Getting the following error on 'flutter packages get' after adding ink_page_indicator:
```
Because every version of flutter_test from sdk depends on meta 1.1.6 and every version of ink_page_indicator depends on meta ^1.1.8, flutter_test from sdk is incompatible with ink_page_indicator.
So, because myapp depends on both ink_page_indicator ^0.1.1 and flutter_test any from sdk, version solving failed.
```

**Comment by BendixMa** [comment]
I'm sorry but I cannot reproduce this error and the issue is also more related to flutter itself than to this package. Are you sure you are using the latest flutter version?

**Comment by badrobot15** [comment]
Yes it was a flutter issue. Flutter upgrade solved the problem
